version: '3.1'
services:
  mysql:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
      - MYSQL_DATABASE=bibliacrista
  app:
    image: python:3.7.2-stretch
    command: bash -c "pip install -r requirements.txt && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0:8000"
    ports:
      - "8000:8000"
    working_dir: /backend
    volumes:
      - "./backend:/backend"
      - "./bkp:/bkp"
    links:
      - mysql