# Generated by Django 2.1.5 on 2019-03-16 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livros',
            fields=[
                ('liv_id', models.AutoField(primary_key=True, serialize=False)),
                ('liv_posicao', models.PositiveIntegerField()),
                ('liv_nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'livros',
            },
        ),
        migrations.CreateModel(
            name='Testamentos',
            fields=[
                ('tes_id', models.AutoField(primary_key=True, serialize=False)),
                ('tes_nome', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'testamentos',
            },
        ),
        migrations.CreateModel(
            name='Versiculos',
            fields=[
                ('ver_id', models.AutoField(primary_key=True, serialize=False)),
                ('ver_capitulo', models.PositiveIntegerField()),
                ('ver_versiculo', models.PositiveIntegerField()),
                ('ver_texto', models.TextField()),
                ('ver_liv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.Livros', verbose_name='Livros')),
            ],
            options={
                'db_table': 'versiculos',
            },
        ),
        migrations.CreateModel(
            name='Versoes',
            fields=[
                ('vrs_id', models.AutoField(primary_key=True, serialize=False)),
                ('vrs_nome', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'versoes',
            },
        ),
        migrations.AddField(
            model_name='versiculos',
            name='ver_vrs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.Versoes', verbose_name='Versão'),
        ),
        migrations.AddField(
            model_name='livros',
            name='liv_tes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.Testamentos', verbose_name='testamentos'),
        ),
        migrations.AlterUniqueTogether(
            name='livros',
            unique_together={('liv_tes', 'liv_posicao')},
        ),
    ]
