# Generated by Django 2.1.5 on 2019-03-17 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
        ('CREATE FULLTEXT INDEX versicle_fulltext_index ON versiculos (ver_texto)',),
        ('DROP INDEX versicle_fulltext_index on versiculos',)
    )
    ]
