# Generated by Django 2.1.5 on 2019-03-19 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblia', '0002_auto_20190317_0359'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dicionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palavra', models.CharField(max_length=70)),
                ('significado', models.CharField(max_length=190)),
                ('ver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblia.Versiculos', verbose_name='Livros')),
            ],
            options={
                'db_table': 'dicionario',
            },
        ),
    ]
