# Generated by Django 2.1.5 on 2019-03-19 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=70)),
                ('meaning', models.TextField()),
            ],
            options={
                'db_table': 'dictionary',
            },
        ),
        migrations.CreateModel(
            name='Testament',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'testament',
            },
        ),
        migrations.CreateModel(
            name='Versicle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('chapter', models.PositiveIntegerField()),
                ('versicle', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Book', verbose_name='Book')),
                ('dictionary', models.ManyToManyField(to='bible.Dictionary')),
            ],
            options={
                'db_table': 'versicle',
            },
        ),
        migrations.CreateModel(
            name='Version',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'version',
            },
        ),
        migrations.AddField(
            model_name='versicle',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Version', verbose_name='Version'),
        ),
        migrations.AddField(
            model_name='book',
            name='testament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bible.Testament', verbose_name='testament'),
        ),
    ]
